### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by gy1965590496** [johnhw/pfilter#16]
after pip install pfilter, when I run the example_filter.py the error occured.
![error](https://user-images.githubusercontent.com/37449166/172749794-51ab9975-7182-4d3a-b83d-22a0f48ef06a.png)

**Comment by arthur-tacca** [comment]
This is an error importing numpy (which is used by this library), not with this library itself.

Plenty of people (to put it mildly) are successfully able to install and import numpy, so this is a problem with your setup, not a big on this or any other library
