### ISSUE TITLE
Improper configuration of modules

### ISSUE THREAD

**Issue by GeoZac** [johnhw/pfilter#2]
The `__init__.py` file in `pfilter` directory requires imports statement with "." preceeding filenames. without which user will encounter `ModuleNotFoundError`

Solution:
https://github.com/johnhw/pfilter/blob/ec55113533caf4c8126a52f8d9a8783ede12bcee/pfilter/__init__.py#L1 should be changed to `from .pfilter import *`

Reference:
https://github.com/numpy/numpy/blob/dea85807c258ded3f75528cce2a444468de93bc1/numpy/__init__.py#L112

https://github.com/tartley/colorama/blob/d69f83f53c0c5aa1081d1f5eebb2dc2df6028f37/colorama/__init__.py#L2

**Comment by johnhw** [comment]
Fixed
