### ISSUE TITLE
Weight_fn parameters

### ISSUE THREAD

**Issue by BoltonBailey** [johnhw/pfilter#7]
In the documentation in pfilter.py line 165, it says that weight_fn should take parameters "real" and "hypothesized" in that order. But when the function is called in line 240,  the "self.hypotheses" attribute is the *first* argument. Shouldn't the self.hypotheses attribute naturally be called as the hypothesized argument?

**Comment by johnhw** [comment]
Ah, yes. I have adjusted the documentation to indicate the correct order (hypothesised, real).
