### ISSUE TITLE
weights don't correspond to particles

### ISSUE THREAD

**Issue by argentum2f** [johnhw/pfilter#8]
While debugging my filter, I plotted my particles with color corresponding to their weights. As the weights seemed to be fairly random, I spent forever looking in various wrong directions before I realized that because of the order of operations, `pf.weights` corresponds to neither `pf.original_particles` or `pf.particles` (where pf is a `ParticleFilter` object). I think this is a bug because the weights are still used even after resampling to calculate mean states, etc. I fixed this by reshuffling  the weights with the particles in the resampling set (line 280):

        # resampling (systematic resampling) step                                                                         
        if self.n_eff < self.n_eff_threshold:                                                                             
            indices = resample(self.weights)                                                                              
            self.particles = self.particles[indices, :]                                                                   
            self.weights = self.weights[indices]

**Comment by johnhw** [comment]
Thank you! I was literally trying to debug this last night -- I thought my plotting code was the source of the issues. This is fixed now.

**Comment by johnhw** [comment]
Actually, the fix suggested would mean that self.weights doesn't normalise to 1.0 when read, which would be unexpected. I've changed it so that weights and original_particles are stored *before* the resampling step is executed, so they correspond to each other, and sum(w)=1.0

**Comment by argentum2f** [comment]
Yep, you're right. Works now.
